In [2]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [4]:
npa = np.array(l)

In [7]:
type(npa)

numpy.ndarray

In [8]:
npa.shape

(5,)

In [9]:
l.append(6)

In [10]:
npa = np.array(l)

In [11]:
l.append('string')

In [13]:
npa = np.array(l)
npa

array(['1', '2', '3', '4', '5', '6', 'string'], dtype='<U11')

In [14]:
l1 = [1,4,9,16]

In [15]:
l + l1

[1, 2, 3, 4, 5, 6, 'string', 1, 4, 9, 16]

In [16]:
np.array(l+l1)

array(['1', '2', '3', '4', '5', '6', 'string', '1', '4', '9', '16'],
      dtype='<U11')

In [17]:
l + 2

TypeError: can only concatenate list (not "int") to list

In [18]:
np.array(l+2)

TypeError: can only concatenate list (not "int") to list

In [19]:
la = [[1,2],[3,4]]

In [20]:
npla = np.array(la)

In [21]:
npla

array([[1, 2],
       [3, 4]])

In [22]:
npla.shape

(2, 2)

In [23]:
npla.reshape(1,4)

array([[1, 2, 3, 4]])

In [24]:
npla.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [26]:
npa = np.array(la, 'float')
npa

array([[1., 2.],
       [3., 4.]])

In [27]:
npa.mean()

2.5

In [32]:
np.describe(npa)

AttributeError: module 'numpy' has no attribute 'describe'

In [39]:
lad = [[1,2],[3,4],[5,6]]
nplad = np.array(lad)

In [34]:
nplad

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
nplad.flatten()

array([1, 2, 3, 4, 5, 6])

In [40]:
nplad.ravel()

array([1, 2, 3, 4, 5, 6])

In [3]:
npr = np.array(np.arange(10))
npr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
npra = np.random.randint(2)
npra

0

In [5]:
np.where(npr > 5, npr)

ValueError: either both or neither of x and y should be given